default:
  image: alpine/helm:3.16.3

release:
  stage: release
  only:
    - main
  script:
    - bash ./scripts/release-charts.sh $CHARTMUSEUM_URL $CHARTMUSEUM_BASIC_AUTH_USER $CHARTMUSEUM_BASIC_AUTH_PASSWORD