apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.nameOverride | default "homer" }}
  namespace: {{ .Values.namespaceOverride | default "homer" }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "homer.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "homer.selectorLabels" . | nindent 4 }}
  type: {{ .Values.service.type }}
  {{- with .Values.service.loadBalancerIP }}
  loadBalancerIP:
  {{- end }}
  internalTrafficPolicy: Cluster
  ports:
    - protocol: TCP
      port: {{ .Values.service.port | default 8088 }}
      targetPort: {{ .Values.deployment.port | default 8088 }}
      name: http
