apiVersion: v2
appVersion: "2024.07.0"
description: A Helm chart for pi-hole
home: https://github.com/pi-hole/docker-pi-hole/
maintainers:
  - email: edward@cheng.sydney
    name: Edward Cheng
name: pi-hole
sources:
  - https://github.com/pi-hole/docker-pi-hole/
version: 1.0.11
