name: RELEASE - Package changed charts and upload to the chartmuseum

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
      packages: write
    name: Build Chart Packages and Upload
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Add Chartmusuem Repository
        run: |
          helm repo add chartmuseum ${{ secrets.CHARTMUSEUM_URL }}
      - name: Push Charts
        id: push_charts
        run: |
          for dir in charts/*; do
            chart_name="$(basename "$dir")"
            version="$(yq '.version' "$dir/Chart.yaml")"
            if ! git rev-parse "$chart_name-${version#v}" &>/dev/null; then
              echo "Pushing chart $chart_name..."
              helm cm-push $dir chartmuseum
            fi
          done