name: RELEASE - Package changed charts and upload to the chartmuseum

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
      packages: write
    name: Build Chart Packages and Upload
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Intall helm-push plugin
        run: |
          helm plugin install https://github.com/chartmuseum/helm-push
      - name: Add Chartmusuem Repository
        run: |
          helm repo add chartmuseum ${{ secrets.CHARTMUSEUM_URL }}
          helm repo update
      - name: Push Charts
        id: push_charts
        run: |
          for dir in charts/*; do
            chart_name="$(basename "$dir")"
            echo $chart_name
            version="$(yq '.version' "$dir/Chart.yaml")"
            chart_ver_url=${{ secrets.CHARTMUSEUM_URL }}/api/charts
            charts=$(curl --location $chart_ver_url)
            existing_versions=$(echo $charts | jq .'"${chart_name}"'[].version)
            if [ -z "${existing_versions}" ]
            then
              echo "Pushing chart $chart_name..."
              echo "helm cm-push -u ${{ secrets.CHARTMUSEUM_BASIC_AUTH_USER }} -p ${{ secrets.CHARTMUSEUM_BASIC_AUTH_PASSWORD }} $dir chartmuseum"
            else
              if [[ ${existing_versions[@]} =~ $version ]] 
              then
                echo "Version $version for chart $chart_name exists, skipping..."
              else
                echo "Pushing chart $chart_name..."
                echo "helm cm-push -u ${{ secrets.CHARTMUSEUM_BASIC_AUTH_USER }} -p ${{ secrets.CHARTMUSEUM_BASIC_AUTH_PASSWORD }} $dir chartmuseum"
              fi
            fi
          done